# Site settings
## Change the values as needed.
title: GrantNichol.com
email: gwnichol@ksu.edu
description: "This websight highlights various projects or anything else I care about."
keywords: "hire, jobs, resume, blog"
#url: "http://bitwiser.in/bitwiser-material" # the base hostname & protocol for your site
url: "https://www.grantnichol.com" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
paginate: 10 
paginate_path: "page:num"

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
links:
  email: gwnichol@ksu.edu
  github: gwnichol
exclude:
  - bower_components
  - README.md
full_name: Grant Nichol

ga_id: UA-149111857-1

plugins:
  - jekyll-paginate

defaults:
  -
    scope:
      path: "_posts"
    values:
      author: "Grant Nichol"
      permalink: "/posts/:title:output_ext"


##set this to enable disqus commenting
#disqus: bitwiser

##set this to enable google analytics
#ga_id: analyticsID
#ga_domain: bitwiser.in
