# Site settings
## Change the values as needed.
title: Grant's Blog
email: gwnichol.m@gmail.com
description: "This is my attempt at a jekyll blog."
keywords: "jekyll, theme, material, blog"
#url: "http://bitwiser.in/bitwiser-material" # the base hostname & protocol for your site
url: "https://gwnichol.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
paginate: 100 
paginate_path: "page:num"

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
links:
  email: gwnichol.m@gmail.com
  github: gwnichol
exclude:
  - bower_components
  - README.md
full_name: Grant Nichol

plugins:
  - jekyll-paginate

##set this to enable disqus commenting
#disqus: bitwiser

##set this to enable google analytics
#ga_id: analyticsID
#ga_domain: bitwiser.in
